### ISSUE TITLE
UDP sockets [Operation not permitted]

### ISSUE THREAD

**Issue by hughsheehy** [SwitchEV/iso15118#179]
Getting a new issue on a new install. 

Everything installs fine, and the EVCC code runs fine. But when I try to run the SECC code, I get this error. 

WARNING    2022-12-15 09:37:47,536 - iso15118.secc.transport.tcp_server (124): Closing TCP server
WARNING    2022-12-15 09:37:47,538 - iso15118.secc.transport.tcp_server (124): Closing TCP server
ERROR    2022-12-15 09:37:47,540 - iso15118.shared.utils (51): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/home/rock/iso15118-master/iso15118/shared/utils.py", line 49, in wait_for_tasks
    task.result()
  File "/home/rock/iso15118-master/iso15118/secc/transport/udp_server.py", line 112, in start
    sock=await self._create_socket(self.iface),
  File "/home/rock/iso15118-master/iso15118/secc/transport/udp_server.py", line 75, in _create_socket
    sock.setsockopt(
PermissionError: [Errno 1] Operation not permitted

From what I can read, this is an issue with UDP ports not being open. So not an issue with this library as such. Just putting this here as info. As and when I find a solution i'll post here and close. 

H

**Comment by hughsheehy** [comment]
went back to this today. i can't seem to find a solution with Ubuntu at all. UDP packets will not flow. 

Any ideas??

**Comment by hughsheehy** [comment]
Googling brought us to a page for a completely different software package that had a similar problem. We were having the problem with Ubuntu 20.04 Server LTS. 

They didn't specifiy if it was Ubuntu or not. But this command fixed their problem...and worked for us too. 

sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/python3.9

As I mentioned, this wasn't needed on any other version of linux that I've used this package on.
