### ISSUE TITLE
The ProfileEntryType/RelativeTimeInterval check has a wrong limit check.

### ISSUE THREAD

**Issue by henri62** [SwitchEV/iso15118#89]
The PMaxType in the DIN 70121:2014 specification has a range of 0 to UINT16_MAX so le=32767 but it rejects a message on a le=255 boundary for the message "ChargeParameterDiscoveryRes".

Also the alias looks wrong and should me 'PMax' iso 'ChargingProfileMaxPower' ?

Also the python code completely breaks on this with a very sloppy stack trace, instead of a descent handling/displaying of the error.

See this dump:

{'V2G_Message': {'Header': {'SessionID': '4242424242424242'}, 'Body': {'ChargeParameterDiscoveryRes': {'ResponseCode': 'OK', 'EVSEProcessing': 'Finished', 'SAScheduleList': {'SAScheduleTuple': [{'SAScheduleTupleID': 1, 'PMaxSchedule': {'PMaxScheduleID': 1, 'PMaxScheduleEntry': [{'RelativeTimeInterval': {'start': 0, 'duration': 28800}, 'PMax': 32767}]}}]}, 'DC_EVSEChargeParameter': {'DC_EVSEStatus': {'EVSEIsolationStatus': 'Invalid', 'EVSEStatusCode': 'EVSE_IsolationMonitoringActive', 'NotificationMaxDelay': 0, 'EVSENotification': 'None'}, 'EVSEMaximumCurrentLimit': {'Multiplier': 0, 'Unit': 'A', 'Value': 180}, 'EVSEMaximumPowerLimit': {'Multiplier': 1, 'Unit': 'W', 'Value': 18000}, 'EVSEMaximumVoltageLimit': {'Multiplier': 0, 'Unit': 'V', 'Value': 1000}, 'EVSEMinimumCurrentLimit': {'Multiplier': 0, 'Unit': 'A', 'Value': 0}, 'EVSEMinimumVoltageLimit': {'Multiplier': 0, 'Unit': 'V', 'Value': 200}, 'EVSEPeakCurrentRipple': {'Multiplier': 0, 'Unit': 'A', 'Value': 1}}}}}}
 XSD namespace: urn:din:70121:2012:MsgDef
INFO    2022-08-03 16:08:55,952 - iso15118.shared.comm_session (215): ChargeParameterDiscoveryRes received
ERROR    2022-08-03 16:08:55,952 - iso15118.shared.comm_session (226): ValidationError: [ErrorWrapper(exc=NumberNotLeError(), loc=('ChargingProfileMaxPower',))]
Traceback (most recent call last):
  File "/home/henri/SwitchEV/iso15118/iso15118/shared/comm_session.py", line 216, in process_message
    await self.current_state.process_message(decoded_message, v2gtp_msg.payload)
  File "/home/henri/SwitchEV/iso15118/iso15118/evcc/states/din_spec_states.py", line 382, in process_message
    schedule_id = await ev_controller.process_sa_schedules_dinspec(
  File "/home/henri/SwitchEV/iso15118/iso15118/evcc/controller/simulator.py", line 469, in process_sa_schedules_dinspec
    profile_entry_details = ProfileEntryDetailsDINSPEC(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ProfileEntryDetails
ChargingProfileMaxPower
  ensure this value is less than or equal to 255 (type=value_error.number.not_le; limit_value=255)
INFO    2022-08-03 16:08:55,953 - iso15118.shared.comm_session (371): The data link will Terminate in 2 seconds and the TCP connection will close in 5 seconds. 
INFO    2022-08-03 16:08:55,953 - iso15118.shared.comm_session (375): Reason: ValidationError occurred while processing message in state ChargeParameterDiscovery: 1 validation error for ProfileEntryDetails
ChargingProfileMaxPower
  ensure this value is less than or equal to 255 (type=value_error.number.not_le; limit_value=255)

**Comment by MarcMueltin** [comment]
Thanks again @henri62 for bringing this to our attention. As mentioned in your previous issue, we'll put some more effort into DIN SPEC very soon. Bear with us. ;)
